# Generated by Django 5.2 on 2025-05-04 14:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuermesseUserCuston',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('is_cliente', models.BooleanField(blank=True, null=True)),
                ('is_caixa', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assign_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_user_assign', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cliente_user_create', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor total')),
                ('data', models.DateField(verbose_name='Data de operação')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('qtd_dinheiro', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor em Dinheiro')),
                ('qtd_cd', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor em cartão de débito')),
                ('qtd_cc', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor em cartão de crédito')),
                ('pix', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Pix')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assign_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clienteCaixa_user_assign', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clienteCaixa_user_create', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quermesse.clientes', verbose_name='Operador')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assign_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clienteUsuario_user_assign', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quermesse.clientes', verbose_name='Clinte')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clienteUsuario_user_create', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='Fiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('datadoc', models.DateField(verbose_name='Data do lançamento')),
                ('datapago', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('is_pago', models.BooleanField(blank=True, null=True, verbose_name='Pago')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assign_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clienteFiado_user_assign', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quermesse.clientes', verbose_name='Clientes')),
                ('cliente_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quermesse.clienteusuario', verbose_name='Cliente usuario')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clienteFiado_user_create', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assign_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clienteProduto_user_assign', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clienteProduto_user_create', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quermesse.caixa', verbose_name='Caixa')),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quermesse.produto', verbose_name='Produtos')),
            ],
            options={
                'unique_together': {('caixa', 'produtos')},
            },
        ),
        migrations.AddField(
            model_name='caixa',
            name='produtos',
            field=models.ManyToManyField(related_name='caixas', through='quermesse.ItemCaixa', to='quermesse.produto'),
        ),
    ]
