# Generated by Django 5.2 on 2025-05-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quermesse.clientes', verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='clienteusuario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quermesse.clientes', verbose_name='Clinte'),
        ),
        migrations.AlterField(
            model_name='fiado',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quermesse.clientes', verbose_name='Clientes'),
        ),
        migrations.AlterField(
            model_name='fiado',
            name='cliente_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quermesse.clienteusuario', verbose_name='Cliente usuario'),
        ),
        migrations.AlterField(
            model_name='itemcaixa',
            name='caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quermesse.caixa', verbose_name='Caixa'),
        ),
        migrations.AlterField(
            model_name='itemcaixa',
            name='produtos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quermesse.produto', verbose_name='Produtos'),
        ),
    ]
