# Generated by Django 5.2 on 2025-05-05 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0002_alter_caixa_cliente_alter_clienteusuario_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcaixa',
            name='caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quermesse.caixa', verbose_name='Caixa'),
        ),
        migrations.AlterField(
            model_name='itemcaixa',
            name='produtos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quermesse.produto', verbose_name='Produtos'),
        ),
    ]
