# Generated by Django 5.2 on 2025-05-07 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0003_alter_itemcaixa_caixa_alter_itemcaixa_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='fiado',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('is_despesa', models.BooleanField(blank=True, verbose_name='Categoria')),
                ('is_entrada', models.BooleanField(blank=True, verbose_name='Entradas')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assign_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_user_assign', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_user_create', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data da operação')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('doc', models.FileField(blank=True, null=True, upload_to='doc_despesas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Nota')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assign_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesa_user_assign', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quermesse.categoria', verbose_name='Categoria')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesa_user_create', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data da operação')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assign_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrada_user_assign', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quermesse.categoria', verbose_name='Categoria')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrada_user_create', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
    ]
