# Generated by Django 5.2 on 2025-05-10 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0005_despesas_datapago_despesas_is_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteusuario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quermesse.clientes', verbose_name='Cliente'),
        ),
    ]
