# Generated by Django 5.2 on 2025-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0006_alter_clienteusuario_cliente'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='caixa',
            index=models.Index(fields=['cliente'], name='quermesse_c_cliente_507c59_idx'),
        ),
    ]
