# Generated by Django 5.2 on 2025-05-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0007_caixa_quermesse_c_cliente_507c59_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='reimpressão',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Reimpressão'),
        ),
    ]
