# Generated by Django 5.2 on 2025-05-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0008_caixa_reimpressão'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='reimpressão',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Reimpressão'),
        ),
    ]
