# Generated by Django 5.2 on 2025-05-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0009_alter_caixa_reimpressão'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caixa',
            old_name='reimpressão',
            new_name='reimpressao',
        ),
    ]
