# Generated by Django 5.2 on 2025-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0010_rename_reimpressao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='reimpressao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Reimpressão'),
        ),
    ]
