# Generated by Django 5.2 on 2025-05-21 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0011_alter_caixa_reimpressao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cortesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da operação')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assign_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cortesia_user_assign', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cortesia_user_create', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCortesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('cortesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quermesse.cortesia', verbose_name='Itens')),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quermesse.produto', verbose_name='Produtos')),
            ],
            options={
                'unique_together': {('cortesia', 'produtos')},
            },
        ),
        migrations.AddField(
            model_name='cortesia',
            name='produtos',
            field=models.ManyToManyField(related_name='cortesias', through='quermesse.ItemCortesia', to='quermesse.produto'),
        ),
    ]
