# Generated by Django 5.2 on 2026-02-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0012_cortesia_itemcortesia_cortesia_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcaixa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcortesia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
