# Generated by Django 5.2 on 2026-04-20 18:06

from django.db import migrations, models


def populate_itemcaixa_valor_unitario(apps, schema_editor):
    ItemCaixa = apps.get_model('quermesse', 'ItemCaixa')
    for item in ItemCaixa.objects.select_related('produtos').all().iterator():
        item.valor_unitario = item.produtos.valor
        item.save(update_fields=['valor_unitario'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0012_cortesia_itemcortesia_cortesia_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcaixa',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Valor unitário'),
        ),
        migrations.RunPython(populate_itemcaixa_valor_unitario, noop_reverse),
    ]
