# Generated by Django 5.2 on 2026-04-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quermesse', '0013_itemcaixa_created_itemcortesia_created'),
        ('quermesse', '0013_itemcaixa_valor_unitario'),
    ]

    operations = [
    ]
